vae:
  latent_dim  : 2
  input_shape : [64, 64, 3]
  alpha       : 1.0
  beta        : 1.0

optimizer:
  epochs    : 200
  batch_size: 128
  lr        : 0.001
  beta_1    : 0.9
  beta_2    : 0.999
  epsilon   : None
  decay     : 0.0
  amsgrad   : false

checkpoint:
  monitor           : loss
  save_weights_only : true
  save_best_only    : false
  save_freq         : epoch
  verbose           : 1

callback:
  save_decoded_image_num : 30

dataset:
  dataset_name: soil

visualize:
  image_num : 10
  figsize   : 15
  digit_size: 64
  channel   : 3
  z0_range  : [-2.0, 3.0]
  z1_range  : [-4.0, 2.0]

model_load:
  model_dir  : "epoch200_batch_size128_dataset_soil_20210920162728"
  model_name : "-1"

normalize:
  min_img : 60
  max_img : 105